pipeline {
    agent any
    environment {
     IMAGE_NAME = "kruthikreddy25/nodejs-cicd"
     CONTAINER_NAME = "nodejs-app"
    }
    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', url: 'https://github.com/skullriderk/NodeJs-Docker.git'

            }

         
        }
        
        stage('Build Docker Image') {
             steps {
                //  sh 'docker build -t kruthikreddy25/nodejs-cicd:latest .'
                  sh '''
                    cd nodejs-cicd
                    docker build -t kruthikreddy25/nodejs-cicd:latest .
                '''
                   }
        }
        
        stage('Docker Login') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'Docker',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )
        ]) {
            sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            '''
        }
    }
}
        stage('Push Image') {
         steps {
        sh 'docker push kruthikreddy25/nodejs-cicd:latest'
         }
}

         stage('Deploy Container') {
            steps {
                sh '''
                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true

                    docker pull ${IMAGE_NAME}:latest

                    docker run -d \
                        --name ${CONTAINER_NAME} \
                        -p 3000:3000 \
                        ${IMAGE_NAME}:latest
                '''
            }
        }
     }
}
